// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Leonardo Colman Lopes

plugins {
  `java-library`
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.kotlin.serialization)
  alias(libs.plugins.detekt)
}

// 17 because :app consumes this module and D8 is happiest with Java 17 bytecode.
kotlin {
  jvmToolchain(17)
  compilerOptions {
    // Kotlin's null checks on Java interop (Intrinsics.checkNotNull*) become mutants no test can
    // kill. :domain is pure Kotlin, so the checks buy nothing here and only dilute the PIT gate.
    freeCompilerArgs.addAll("-Xno-call-assertions", "-Xno-param-assertions", "-Xno-receiver-assertions")
  }
}

/**
 * Classpath used to launch PIT, kept apart so the mutation engine never leaks into the artifact.
 */
val pitest: Configuration by configurations.creating {
  isCanBeConsumed = false
  isCanBeResolved = true
}

dependencies {
  api(libs.kotlinx.serialization.json)

  testImplementation(libs.bundles.kotest)

  // Kotest ships its own PIT test plugin, so PIT drives the Kotest engine directly.
  pitest(libs.pitest.command.line)
  pitest(libs.kotest.pitest)

  detektPlugins(libs.detekt.formatting)
}

tasks.test {
  useJUnitPlatform()
}

detekt {
  buildUponDefaultConfig = true
  config.setFrom(rootProject.file("config/detekt/detekt.yml"))
}

/**
 * Mutation testing, gated at 90% killed mutants (dossier §10, ADR 0016).
 *
 * The `info.solidsoft.pitest` plugin does not apply on Gradle 9 (it reads the removed
 * `ReportingExtension.baseDir`), so PIT runs from its command line entrypoint instead.
 */
val pitestTask = tasks.register<JavaExec>("pitest") {
  group = "verification"
  description = "Runs PIT mutation testing and fails below 90% killed mutants"

  val testSourceSet = sourceSets.test.get()
  val mutableCodePaths = sourceSets.main.get().output.classesDirs
  val codeUnderTest = testSourceSet.runtimeClasspath
  val sourceDirs = files("src/main/kotlin")
  val reportDir = layout.buildDirectory.dir("reports/pitest")
  val classpathFile = layout.buildDirectory.file("tmp/pitest/classpath.txt")

  dependsOn(tasks.testClasses)
  inputs.files(codeUnderTest).withPropertyName("codeUnderTest")
  inputs.files(sourceDirs).withPropertyName("sourceDirs")
  outputs.dir(reportDir).withPropertyName("report")

  javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(17) }
  mainClass = "org.pitest.mutationtest.commandline.MutationCoverageReport"
  // Test runtime first, so PIT's minions load exactly the jars the test task loads.
  classpath(codeUnderTest)
  classpath(pitest)

  args(
    "--classPathFile=${classpathFile.get().asFile.absolutePath}",
    "--mutableCodePaths=${mutableCodePaths.joinToString(",") { it.absolutePath }}",
    "--sourceDirs=${sourceDirs.joinToString(",") { it.absolutePath }}",
    "--reportDir=${reportDir.get().asFile.absolutePath}",
    "--targetClasses=br.com.colman.palavramento.domain.*",
    // PIT only hands specs matching this glob to the engine: every Kotest spec must be named *Test.
    "--targetTests=br.com.colman.palavramento.domain.*Test",
    // Code generated by the kotlinx.serialization plugin, not ours to test. The `protocol` package
    // is excluded too: it is plain DTOs with no branching logic, already covered by round-trip
    // serialization tests, and its @Serializable data classes generate mutants (constructor
    // parameter defaults, equals/hashCode) that round-trip tests do not exercise line by line.
    "--excludedClasses=*\$\$serializer,*\$inlined\$*,br.com.colman.palavramento.domain.protocol.*",
    "--testPlugin=Kotest",
    "--mutationThreshold=90",
    // Property based specs are slow enough that PIT's 4s default kills healthy minions.
    "--timeoutConst=10000",
    "--outputFormats=HTML,XML",
    "--timestampedReports=false",
    "--failWhenNoMutations=false",
  )

  doFirst {
    classpathFile.get().asFile.apply {
      parentFile.mkdirs()
      writeText(codeUnderTest.filter { it.exists() }.joinToString("\n") { it.absolutePath })
    }
    // Added here so the core count of whichever machine runs the build stays out of the inputs.
    args("--threads=${Runtime.getRuntime().availableProcessors()}")
  }
}

// Not part of `check` (ADR 0023): mutation runs weekly in CI and by hand now and then, and the
// README badge shows the resulting test strength. The threshold above still fails this task.
